apiVersion: v1
kind: ConfigMap

metadata:
  name: employee-app-config

data:

  APP_NAME: "Employee Management API"

  APP_ENV: "production"

  MYSQL_HOST: "mysql-service"

  MYSQL_PORT: "3306"

  MYSQL_DATABASE: "employee_db"

  LOG_LEVEL: "INFO"